DROP TABLE IF EXISTS "project_team" CASCADE;
DROP TABLE IF EXISTS "project_member" CASCADE;
DROP TABLE IF EXISTS "team_member" CASCADE;
DROP TABLE IF EXISTS "team" CASCADE;
ALTER TABLE "project" DROP COLUMN IF EXISTS "lead_user_id";
