"use client";

import { useMemo, useState } from "react";
import { Check, Copy, FileDown, Link2, Printer, Sparkles } from "lucide-react";
import { Markdown } from "@/components/q/markdown";
import { downloadFile, markdownToHtmlDoc, slugify } from "@/lib/report-export";

type ApiType = "project" | "resource" | "portfolio" | "manager" | "member";
type Period = "week" | "month";

interface ProjectOpt {
  id: string;
  code: string;
  name: string;
}
interface PersonOpt {
  id: string;
  name: string;
  department: string | null;
}

// UI "kinds" map to API report types + a target. Keeping them separate lets us show
// "My workload" (resource/self) and "Person" (resource/other) as distinct, clear choices.
type Kind = "mywork" | "myload" | "project" | "person" | "portfolio" | "delivery";
interface KindDef {
  kind: Kind;
  label: string;
  hint: string;
  apiType: ApiType;
  needsProject?: boolean;
  needsPerson?: boolean;
  hasPeriod: boolean;
  managerOnly?: boolean;
}

const KINDS: KindDef[] = [
  { kind: "mywork", label: "My work", hint: "Your projects, plus risks & blockers you own", apiType: "member", hasPeriod: true },
  { kind: "myload", label: "My workload", hint: "Your allocation across projects", apiType: "resource", hasPeriod: true },
  { kind: "project", label: "Project", hint: "Status, activity, resources, risks & issues", apiType: "project", needsProject: true, hasPeriod: true, managerOnly: true },
  { kind: "person", label: "Person", hint: "A team member's workload & activity", apiType: "resource", needsPerson: true, hasPeriod: true, managerOnly: true },
  { kind: "portfolio", label: "Portfolio", hint: "Executive: health, attention, milestones", apiType: "portfolio", hasPeriod: false, managerOnly: true },
  { kind: "delivery", label: "Delivery", hint: "Tasks by status, open risks, blockers, workload", apiType: "manager", hasPeriod: false, managerOnly: true },
];

const CARD = "rounded-[16px] border border-[var(--cardbd)] shadow-[var(--cardsh)] backdrop-blur-[var(--glassblur)] backdrop-saturate-[1.25]";

interface CurrentReport {
  title: string;
  periodLabel: string;
  markdown: string;
  usedAi: boolean;
  apiType: ApiType;
  targetId?: string;
}

export function ReportsClient({
  canReports,
  me,
  tenantName,
  projects,
  people,
}: {
  canReports: boolean;
  me: { id: string; name: string };
  tenantName: string;
  projects: ProjectOpt[];
  people: PersonOpt[];
}) {
  const kinds = useMemo(() => KINDS.filter((k) => canReports || !k.managerOnly), [canReports]);
  const [kind, setKind] = useState<Kind>("mywork");
  const [period, setPeriod] = useState<Period>("week");
  const [projectId, setProjectId] = useState(projects[0]?.id ?? "");
  const [personId, setPersonId] = useState(people[0]?.id ?? "");

  const [report, setReport] = useState<CurrentReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);
  const [copied, setCopied] = useState<"" | "link" | "text">("");

  const def = kinds.find((k) => k.kind === kind)!;
  const canRun = !loading && (!def.needsProject || projectId) && (!def.needsPerson || personId);

  function targetFor(d: KindDef): string | undefined {
    if (d.needsProject) return projectId;
    if (d.needsPerson) return personId;
    if (d.apiType === "member" || d.apiType === "resource") return me.id; // own reports
    return undefined;
  }

  async function generate(d: KindDef, p: Period) {
    setLoading(true);
    setError(null);
    setShareUrl(null);
    setCopied("");
    const targetId = targetFor(d);
    try {
      const res = await fetch("/api/q/report", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ type: d.apiType, targetId, period: d.hasPeriod ? p : "all" }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error?.message ?? "Couldn't generate that report.");
      setReport({
        title: json.title,
        periodLabel: json.periodLabel,
        markdown: json.markdown,
        usedAi: Boolean(json.usedAi),
        apiType: d.apiType,
        targetId,
      });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
      setReport(null);
    } finally {
      setLoading(false);
    }
  }

  function footer(): string {
    const when = new Date().toLocaleString("en-GB", { dateStyle: "long", timeStyle: "short" });
    return `${tenantName} · ${report?.periodLabel ?? ""} · Generated by Q on ${when}`;
  }

  function onDownloadMd() {
    if (!report) return;
    const doc = `${report.markdown}\n\n---\n_${footer()}_\n`;
    downloadFile(`${slugify(report.title)}.md`, doc, "text/markdown;charset=utf-8");
  }

  function onDownloadHtml() {
    if (!report) return;
    const html = markdownToHtmlDoc(report.markdown, { title: report.title, footer: footer() });
    downloadFile(`${slugify(report.title)}.html`, html, "text/html;charset=utf-8");
  }

  async function onCopyText() {
    if (!report) return;
    await navigator.clipboard.writeText(report.markdown);
    setCopied("text");
    setTimeout(() => setCopied(""), 1800);
  }

  async function onShare() {
    if (!report || sharing) return;
    setSharing(true);
    setError(null);
    try {
      const res = await fetch("/api/q/report/share", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          type: report.apiType,
          targetId: report.targetId,
          title: report.title,
          periodLabel: report.periodLabel,
          markdown: report.markdown,
          usedAi: report.usedAi,
        }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error?.message ?? "Couldn't create a share link.");
      const url = `${window.location.origin}${json.path}`;
      setShareUrl(url);
      await navigator.clipboard.writeText(url).then(
        () => {
          setCopied("link");
          setTimeout(() => setCopied(""), 1800);
        },
        () => {},
      );
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't create a share link.");
    } finally {
      setSharing(false);
    }
  }

  return (
    <main className="mx-auto grid w-full max-w-[1120px] grid-cols-1 items-start gap-4 p-[22px_24px_90px] lg:grid-cols-[400px_minmax(0,1fr)]">
      {/* Left column: header + builder */}
      <div className="flex flex-col gap-3.5">
        <div className="[animation:rise_.5s_cubic-bezier(.22,1,.36,1)_both]">
          <div className="mb-1.5 font-mono rv:font-sans text-[10px] rv:text-overline font-semibold uppercase tracking-[2.4px] text-[var(--ink4)]">Reports centre</div>
          <h1 className="font-heading text-[27px] rv:text-heading-lg font-bold tracking-[-.8px] text-[var(--qink)]">Reports</h1>
          <p className="mt-1.5 text-[13px] rv:text-body-sm text-[var(--ink3)]">
            Exports are downloadable (.md / print-ready) and shareable via a tenant-scoped link.
          </p>
        </div>

        <div className={`flex flex-col gap-4 p-[18px] [animation:rise_.55s_cubic-bezier(.22,1,.36,1)_.05s_both] ${CARD}`} style={{ background: "var(--cardbg)" }}>
          {/* Report kind */}
          <Section label="Report">
            <div className="grid grid-cols-2 gap-1.5">
              {kinds.map((k) => {
                const active = k.kind === kind;
                return (
                  <button
                    key={k.kind}
                    type="button"
                    onClick={() => {
                      setKind(k.kind);
                      setShareUrl(null);
                    }}
                    aria-pressed={active}
                    className="rounded-[10px] border px-2.5 py-2 text-left text-[12px] font-semibold text-[var(--qink)] transition-colors"
                    style={{
                      borderColor: active ? "var(--brand)" : "var(--hair)",
                      background: active ? "color-mix(in oklab, var(--brand) 10%, transparent)" : "transparent",
                    }}
                  >
                    {k.label}
                  </button>
                );
              })}
            </div>
            <p className="mt-1 text-[11px] leading-[1.45] text-[var(--ink4)]">{def.hint}</p>
          </Section>

          {def.needsProject && (
            <Section label="Project">
              <NativeSelect value={projectId} onChange={setProjectId}>
                {projects.map((p) => (
                  <option key={p.id} value={p.id}>{p.name} ({p.code})</option>
                ))}
              </NativeSelect>
            </Section>
          )}
          {def.needsPerson && (
            <Section label="Person">
              <NativeSelect value={personId} onChange={setPersonId}>
                {people.map((p) => (
                  <option key={p.id} value={p.id}>{p.name}{p.department ? ` · ${p.department}` : ""}</option>
                ))}
              </NativeSelect>
            </Section>
          )}

          {def.hasPeriod && (
            <Section label="Period">
              <div className="flex gap-1.5">
                {(["week", "month"] as Period[]).map((p) => {
                  const active = period === p;
                  return (
                    <button
                      key={p}
                      type="button"
                      onClick={() => setPeriod(p)}
                      aria-pressed={active}
                      className="rounded-full border px-[13px] py-[7px] text-[11.5px] font-semibold transition-colors"
                      style={{
                        borderColor: active ? "var(--brand)" : "var(--hair)",
                        color: active ? "var(--brand)" : "var(--ink3)",
                        background: active ? "color-mix(in oklab, var(--brand) 10%, transparent)" : "transparent",
                      }}
                    >
                      {p === "week" ? "Weekly" : "Monthly"}
                    </button>
                  );
                })}
              </div>
            </Section>
          )}

          <button
            type="button"
            disabled={!canRun}
            onClick={() => generate(def, period)}
            className="flex items-center justify-center gap-2 rounded-[11px] bg-[var(--brand)] p-3 text-[13px] font-bold text-[var(--onbrand)] shadow-[0_4px_20px_color-mix(in_oklab,var(--brand)_var(--glowA),transparent)] transition-opacity disabled:opacity-50"
          >
            <Sparkles className="size-4" /> {loading ? "Generating…" : "Generate report"}
          </button>
          <p className="text-[11px] leading-[1.5] text-[var(--ink4)]">
            Q drafts the narrative from live project, risk and workload data — you review before it leaves the building.
          </p>
          {!canReports && (
            <p className="text-[11px] leading-[1.5] text-[var(--ink5)]">
              You can export your own reports. Project, person and portfolio reports are available to project managers and executives.
            </p>
          )}
        </div>
      </div>

      {/* Preview + actions */}
      <div className={`min-h-[440px] overflow-hidden [animation:rise_.55s_cubic-bezier(.22,1,.36,1)_.08s_both] ${CARD}`} style={{ background: "var(--cardbg)" }}>
        {error && (
          <div className="m-4 rounded-lg border border-[color-mix(in_oklab,var(--bad)_45%,transparent)] bg-[color-mix(in_oklab,var(--bad)_12%,transparent)] px-3 py-2 text-[12.5px] text-[var(--bad)]">
            {error}
          </div>
        )}

        {!report && !loading && !error && (
          <div className="flex h-full min-h-[440px] flex-col items-center justify-center gap-3 p-8 text-center text-[var(--ink4)]">
            <span aria-hidden className="grid grid-cols-2 grid-rows-2 gap-1 opacity-40">
              <span className="size-3.5 rounded-[4px] bg-[var(--ink4)]" />
              <span className="size-3.5 rounded-[4px]" style={{ background: "color-mix(in oklab, var(--ink4) 45%, transparent)" }} />
              <span className="size-3.5 rounded-[4px]" style={{ background: "color-mix(in oklab, var(--ink4) 45%, transparent)" }} />
              <span className="size-3.5 rounded-[4px] bg-[var(--ink4)]" />
            </span>
            <span className="text-[12.5px]">Choose a report and period, then generate — the preview lands here.</span>
          </div>
        )}

        {loading && (
          <div className="flex flex-col gap-3 p-5">
            <div className="flex items-center gap-2 text-[13px] text-[var(--ink3)]">
              <Sparkles className="size-4 animate-pulse text-brand" /> Q is analysing your data…
            </div>
            {[80, 95, 70, 88, 60, 75].map((w, i) => (
              <div key={i} className="h-3 rounded bg-[var(--wash2)] [animation:pulseGlow_1.6s_infinite]" style={{ width: `${w}%` }} />
            ))}
          </div>
        )}

        {report && !loading && (
          <div className="flex flex-col">
            <div className="flex flex-wrap items-center gap-2 border-b border-[var(--hair)] p-[12px_16px]">
              <div className="mr-auto min-w-0">
                <div className="truncate font-heading text-[14px] rv:text-heading-xs font-bold text-[var(--qink)]">{report.title}</div>
                <div className="font-mono text-[9.5px] uppercase tracking-[1.2px] text-[var(--ink4)]">{report.periodLabel}</div>
              </div>
              <ToolButton onClick={onDownloadMd} icon={<FileDown className="size-3.5" />} label="Markdown" />
              <ToolButton onClick={onDownloadHtml} icon={<Printer className="size-3.5" />} label="HTML / PDF" />
              <ToolButton onClick={onCopyText} icon={copied === "text" ? <Check className="size-3.5" /> : <Copy className="size-3.5" />} label={copied === "text" ? "Copied" : "Copy"} />
              <ToolButton
                onClick={onShare}
                icon={copied === "link" ? <Check className="size-3.5" /> : <Link2 className="size-3.5" />}
                label={sharing ? "Sharing…" : copied === "link" ? "Link copied" : "Share"}
                primary
              />
            </div>

            {shareUrl && (
              <div className="flex items-center gap-2 border-b border-[var(--hair)] bg-[var(--wash)] p-[10px_16px]">
                <Link2 className="size-3.5 flex-none text-brand" />
                <input
                  readOnly
                  value={shareUrl}
                  onFocus={(e) => e.currentTarget.select()}
                  className="flex-1 bg-transparent text-[11.5px] text-[var(--ink2)] outline-none"
                />
                <span className="flex-none text-[10.5px] text-[var(--ink5)]">Anyone in {tenantName} with the link &amp; an account</span>
              </div>
            )}

            <div className="p-5">
              <div className="rounded-[14px] border border-[var(--hair2)] bg-[var(--qbg)] p-4">
                <Markdown text={report.markdown} />
              </div>
              <div className="mt-2.5 font-mono text-[9.5px] uppercase tracking-[1.2px] text-[var(--ink5)]">
                {report.usedAi
                  ? "Generated by Q from your tenant data · verify before sharing externally"
                  : "Generated deterministically from your live data (AI provider not configured)"}
              </div>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-2">
      <label className="font-mono rv:font-sans text-[9px] rv:text-overline font-semibold uppercase tracking-[1.8px] text-[var(--ink4)]">{label}</label>
      {children}
    </div>
  );
}

function NativeSelect({ value, onChange, children }: { value: string; onChange: (v: string) => void; children: React.ReactNode }) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className="rounded-[10px] border border-[var(--hair)] bg-[var(--qbg)] px-3 py-2 text-[12.5px] text-[var(--qink)] outline-none focus:border-[color-mix(in_oklab,var(--brand)_50%,transparent)]"
    >
      {children}
    </select>
  );
}

function ToolButton({ onClick, icon, label, primary }: { onClick: () => void; icon: React.ReactNode; label: string; primary?: boolean }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[11px] font-semibold transition-colors"
      style={
        primary
          ? { borderColor: "var(--brand)", color: "var(--brand)", background: "color-mix(in oklab, var(--brand) 10%, transparent)" }
          : { borderColor: "var(--hair)", color: "var(--ink3)" }
      }
    >
      {icon}
      {label}
    </button>
  );
}
