import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { auth } from "@/lib/auth";
import { getShareByToken } from "@/server/q/shares";
import { Markdown } from "@/components/q/markdown";
import { ShareActions } from "./share-actions";

// Shared report view. Lives inside the authenticated (app) area, so the viewer must be
// signed in; getShareByToken runs under the tenant's RLS context, so a token only resolves
// for a colleague in the same tenant — a link is never a public, cross-tenant leak.
export default async function SharedReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const session = await auth();
  if (!session?.user) return null;
  const ctx = { tenantId: session.user.tenantId, userId: session.user.id, roles: session.user.roles, permissions: session.user.permissions };

  const report = await getShareByToken(ctx, token);

  if (!report) {
    return (
      <main className="mx-auto flex w-full max-w-[720px] flex-col items-center gap-3 p-[80px_24px] text-center">
        <h1 className="text-[20px] font-bold text-[var(--qink)]">Report not found</h1>
        <p className="text-[13px] text-[var(--ink4)]">
          This shared report doesn&apos;t exist, or it belongs to a different organisation.
        </p>
        <Link href="/reports" className="mt-2 text-[13px] font-semibold text-brand hover:underline">
          Go to Reports
        </Link>
      </main>
    );
  }

  const footer = `${session.user.tenantName} · ${report.periodLabel} · Shared${
    report.authorName ? ` by ${report.authorName}` : ""
  }`;

  return (
    <main className="mx-auto flex w-full max-w-[820px] flex-col gap-5 p-[26px_24px_90px]">
      <Link href="/reports" className="flex w-fit items-center gap-1.5 text-[12px] font-semibold text-[var(--ink4)] hover:text-brand">
        <ArrowLeft className="size-3.5" /> Reports
      </Link>

      <div className="flex flex-wrap items-end justify-between gap-3">
        <div className="min-w-0">
          <div className="mb-2 text-[10.5px] font-bold uppercase tracking-[2.2px] text-brand">
            Shared report · {session.user.tenantName}
          </div>
          <h1 className="text-[24px] font-bold tracking-[-0.5px] text-[var(--qink)]">{report.title}</h1>
          <p className="mt-1 text-[12px] text-[var(--ink4)]">
            {report.periodLabel}
            {report.authorName ? ` · shared by ${report.authorName}` : ""} ·{" "}
            {new Date(report.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}
          </p>
        </div>
        <ShareActions title={report.title} markdown={report.markdown} footer={footer} />
      </div>

      <div className="rounded-2xl border border-[var(--w07)] bg-[var(--qcard)] p-5">
        <Markdown text={report.markdown} />
      </div>
      <div className="text-[10.5px] text-[var(--ink5)]">
        {report.usedAi
          ? "Generated by Q from tenant data at publish time. This is a point-in-time snapshot."
          : "Generated deterministically from live data at publish time. This is a point-in-time snapshot."}
      </div>
    </main>
  );
}
